### ISSUE TITLE
Can't convert OST file to PST file

### ISSUE THREAD

**Issue by hoangcuongflp** [aspose-email/Aspose.Email-Python-Dotnet#3]
class ConvertOSTToPST
    {
        public static void Run()
        {
            // ExStart:ConvertOSTToPST
            string dataDir = RunExamples.GetDataDir_Outlook();

            // Load the Outlook file
            **### string path = dataDir + "PersonalStorage.pst";**

            // Get the Display Name of the file
            using (PersonalStorage ost = PersonalStorage.FromFile(path))
            {
                ost.SaveAs(dataDir + "ConvertOSTToPST_out.pst", FileFormat.Pst);
            }
            // ExEnd:ConvertOSTToPST
        }
    }

The input is .PST file, output is the same. What was converted???. This is fake project.

**Comment by andreypotapovaspose** [comment]
@hoangcuongflp,
We apologize for the long answer. Thank you for the incorrect example found.

I logged the issue with ID EMAILNET-40483 in our tracking system. Our development team will fix it.

If you have any questions or issues found, please post them on [Aspose.Email forum](https://forum.aspose.com/c/email/). We will reply to you and do our best to resolve the issues.

**Comment by tahir-manzoor** [comment]
@hoangcuongflp 

The issue EMAILNET-40483 has been resolved. You can get the code example from here:
https://github.com/aspose-email/Aspose.Email-for-.NET/blob/master/Examples/CSharp/Outlook/ConvertOSTToPST.cs
